services:
  web:
    build: .
    container_name: kiralama_web
    restart: unless-stopped
    command: gunicorn --reload --bind 0.0.0.0:10000 run:app
    ports:
      - "5000:10000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:gizlisifre@db:5432/kiralama_db
      - TEMPLATES_AUTO_RELOAD=true
      - DISABLE_STATIC_CACHE=true
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: kiralama_veritabani
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gizlisifre
      POSTGRES_DB: kiralama_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: