"""arac_bakim_tablosu_ekle

Revision ID: b74120ad3067
Revises: a7f0d91c3b42
Create Date: 2026-04-05 08:24:08.014849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74120ad3067'
down_revision = 'a7f0d91c3b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arac_bakim',
    sa.Column('arac_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('bakim_tipi', sa.String(length=50), nullable=False),
    sa.Column('yapilan_islem', sa.String(length=500), nullable=True),
    sa.Column('maliyet', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kilometre', sa.Integer(), nullable=True),
    sa.Column('yapan_yer', sa.String(length=200), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('sonraki_bakim_tarihi', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arac_id'], ['araclar.id'], name=op.f('fk_arac_bakim_arac_id_araclar')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arac_bakim'))
    )
    with op.batch_alter_table('arac_bakim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arac_bakim_arac_id'), ['arac_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_arac_bakim_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_arac_bakim_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personel_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('personel_izin', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_personel_izin_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel_izin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personel_izin_is_deleted'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personel_is_active'))

    with op.batch_alter_table('arac_bakim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arac_bakim_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_arac_bakim_is_active'))
        batch_op.drop_index(batch_op.f('ix_arac_bakim_arac_id'))

    op.drop_table('arac_bakim')
    # ### end Alembic commands ###
