"""Postgres ilk kurulum

Revision ID: bf17d13659c3
Revises: 
Create Date: 2026-04-02 21:10:21.999079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf17d13659c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('company_short_name', sa.String(length=80), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=False),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_phone', sa.String(length=30), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('company_website', sa.String(length=200), nullable=True),
    sa.Column('invoice_title', sa.String(length=150), nullable=True),
    sa.Column('invoice_address', sa.Text(), nullable=True),
    sa.Column('invoice_tax_office', sa.String(length=100), nullable=True),
    sa.Column('invoice_tax_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_mersis_no', sa.String(length=16), nullable=True),
    sa.Column('invoice_iban', sa.String(length=64), nullable=True),
    sa.Column('invoice_notes', sa.Text(), nullable=True),
    sa.Column('kiralama_form_start_no', sa.Integer(), nullable=False),
    sa.Column('genel_sozlesme_start_no', sa.Integer(), nullable=False),
    sa.Column('kiralama_form_prefix', sa.String(length=10), nullable=False),
    sa.Column('genel_sozlesme_prefix', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('firma',
    sa.Column('firma_adi', sa.String(length=150), nullable=False),
    sa.Column('yetkili_adi', sa.String(length=100), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('eposta', sa.String(length=120), nullable=True),
    sa.Column('iletisim_bilgileri', sa.Text(), nullable=False),
    sa.Column('tckn', sa.String(length=11), nullable=True),
    sa.Column('mersis_no', sa.String(length=16), nullable=True),
    sa.Column('ticaret_sicil_no', sa.String(length=50), nullable=True),
    sa.Column('adres_satiri_1', sa.String(length=250), nullable=True),
    sa.Column('adres_satiri_2', sa.String(length=250), nullable=True),
    sa.Column('ilce', sa.String(length=100), nullable=True),
    sa.Column('il', sa.String(length=100), nullable=True),
    sa.Column('posta_kodu', sa.String(length=20), nullable=True),
    sa.Column('ulke', sa.String(length=100), nullable=False),
    sa.Column('ulke_kodu', sa.String(length=2), nullable=False),
    sa.Column('web_sitesi', sa.String(length=200), nullable=True),
    sa.Column('etiket_uuid', sa.String(length=120), nullable=True),
    sa.Column('is_efatura_mukellefi', sa.Boolean(), nullable=False),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=False),
    sa.Column('vergi_no', sa.String(length=50), nullable=False),
    sa.Column('is_musteri', sa.Boolean(), nullable=False),
    sa.Column('is_tedarikci', sa.Boolean(), nullable=False),
    sa.Column('bakiye', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sozlesme_no', sa.String(length=50), nullable=True),
    sa.Column('sozlesme_rev_no', sa.Integer(), nullable=True),
    sa.Column('sozlesme_tarihi', sa.Date(), nullable=True),
    sa.Column('bulut_klasor_adi', sa.String(length=100), nullable=True),
    sa.Column('imza_yetkisi_kontrol_edildi', sa.Boolean(), nullable=False),
    sa.Column('imza_yetkisi_kontrol_tarihi', sa.DateTime(), nullable=True),
    sa.Column('imza_yetkisi_kontrol_eden_id', sa.Integer(), nullable=True),
    sa.Column('imza_arsiv_notu', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firma')),
    sa.UniqueConstraint('bulut_klasor_adi', name=op.f('uq_firma_bulut_klasor_adi'))
    )
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firma_eposta'), ['eposta'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_etiket_uuid'), ['etiket_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_firma_adi'), ['firma_adi'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_is_musteri'), ['is_musteri'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_is_tedarikci'), ['is_tedarikci'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_tckn'), ['tckn'], unique=False)
        batch_op.create_index(batch_op.f('ix_firma_vergi_no'), ['vergi_no'], unique=True)

    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_log'))
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_username'), ['username'], unique=False)

    op.create_table('subeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isim', sa.String(length=100), nullable=False),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('konum_linki', sa.String(length=500), nullable=True),
    sa.Column('yetkili_kisi', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subeler'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('araclar',
    sa.Column('plaka', sa.String(length=20), nullable=False),
    sa.Column('arac_tipi', sa.String(length=50), nullable=True),
    sa.Column('marka_model', sa.String(length=100), nullable=True),
    sa.Column('sube_id', sa.Integer(), nullable=True),
    sa.Column('muayene_tarihi', sa.Date(), nullable=True),
    sa.Column('sigorta_tarihi', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], name=op.f('fk_araclar_sube_id_subeler')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_araclar'))
    )
    with op.batch_alter_table('araclar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_araclar_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_araclar_plaka'), ['plaka'], unique=True)

    op.create_table('cari_hareket',
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=False),
    sa.Column('yon', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kalan_tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('durum', sa.String(length=10), nullable=False),
    sa.Column('kaynak_modul', sa.String(length=50), nullable=True),
    sa.Column('kaynak_id', sa.Integer(), nullable=True),
    sa.Column('ozel_id', sa.Integer(), nullable=True),
    sa.Column('belge_no', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.Column('referans_hareket_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("durum IN ('acik', 'kapali', 'iptal')", name=op.f('ck_cari_hareket_check_cari_hareket_durum')),
    sa.CheckConstraint("yon IN ('gelen', 'giden')", name=op.f('ck_cari_hareket_check_cari_hareket_yon')),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name=op.f('fk_cari_hareket_firma_id_firma')),
    sa.ForeignKeyConstraint(['referans_hareket_id'], ['cari_hareket.id'], name=op.f('fk_cari_hareket_referans_hareket_id_cari_hareket')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cari_hareket'))
    )
    with op.batch_alter_table('cari_hareket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cari_hareket_belge_no'), ['belge_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_durum'), ['durum'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_firma_id'), ['firma_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_kaynak_id'), ['kaynak_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_kaynak_modul'), ['kaynak_modul'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_tarih'), ['tarih'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_vade_tarihi'), ['vade_tarihi'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_hareket_yon'), ['yon'], unique=False)

    op.create_table('ekipman',
    sa.Column('kod', sa.String(length=100), nullable=False),
    sa.Column('yakit', sa.String(length=50), nullable=False),
    sa.Column('tipi', sa.String(length=100), nullable=False),
    sa.Column('marka', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('seri_no', sa.String(length=100), nullable=False),
    sa.Column('calisma_yuksekligi', sa.Integer(), nullable=False),
    sa.Column('kaldirma_kapasitesi', sa.Integer(), nullable=False),
    sa.Column('agirlik', sa.Float(), nullable=True),
    sa.Column('ic_mekan_uygun', sa.Boolean(), nullable=False),
    sa.Column('arazi_tipi_uygun', sa.Boolean(), nullable=False),
    sa.Column('genislik', sa.Float(), nullable=True),
    sa.Column('uzunluk', sa.Float(), nullable=True),
    sa.Column('kapali_yukseklik', sa.Float(), nullable=True),
    sa.Column('uretim_yili', sa.Integer(), nullable=False),
    sa.Column('calisma_durumu', sa.String(length=50), nullable=False),
    sa.Column('giris_maliyeti', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=False),
    sa.Column('temin_doviz_kuru_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('temin_doviz_kuru_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sube_id', sa.Integer(), nullable=True),
    sa.Column('firma_tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_tedarikci_id'], ['firma.id'], name=op.f('fk_ekipman_firma_tedarikci_id_firma')),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], name=op.f('fk_ekipman_sube_id_subeler')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ekipman')),
    sa.UniqueConstraint('firma_tedarikci_id', 'seri_no', name='_tedarikci_seri_no_uc')
    )
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ekipman_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ekipman_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_ekipman_kod'), ['kod'], unique=True)
        batch_op.create_index(batch_op.f('ix_ekipman_seri_no'), ['seri_no'], unique=False)

    op.create_table('kasa',
    sa.Column('kasa_adi', sa.String(length=100), nullable=False),
    sa.Column('tipi', sa.String(length=20), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=False),
    sa.Column('banka_sube_adi', sa.String(length=120), nullable=True),
    sa.Column('sube_id', sa.Integer(), nullable=True),
    sa.Column('bakiye', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sube_id'], ['subeler.id'], name=op.f('fk_kasa_sube_id_subeler')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kasa'))
    )
    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kasa_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_kasa_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('kiralama',
    sa.Column('kiralama_form_no', sa.String(length=100), nullable=False),
    sa.Column('makine_calisma_adresi', sa.Text(), nullable=True),
    sa.Column('kiralama_olusturma_tarihi', sa.Date(), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=False),
    sa.Column('doviz_kuru_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('doviz_kuru_eur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('firma_musteri_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_musteri_id'], ['firma.id'], name=op.f('fk_kiralama_firma_musteri_id_firma')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kiralama')),
    sa.UniqueConstraint('kiralama_form_no', name=op.f('uq_kiralama_kiralama_form_no'))
    )
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiralama_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiralama_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stok_karti',
    sa.Column('parca_kodu', sa.String(length=100), nullable=False),
    sa.Column('parca_adi', sa.String(length=250), nullable=False),
    sa.Column('mevcut_stok', sa.Integer(), nullable=False),
    sa.Column('varsayilan_tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['varsayilan_tedarikci_id'], ['firma.id'], name=op.f('fk_stok_karti_varsayilan_tedarikci_id_firma')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stok_karti'))
    )
    with op.batch_alter_table('stok_karti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stok_karti_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_stok_karti_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stok_karti_parca_kodu'), ['parca_kodu'], unique=True)

    op.create_table('takvim_hatirlatma',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('baslik', sa.String(length=150), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_takvim_hatirlatma_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takvim_hatirlatma'))
    )
    with op.batch_alter_table('takvim_hatirlatma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_takvim_hatirlatma_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_takvim_hatirlatma_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_takvim_hatirlatma_tarih'), ['tarih'], unique=False)
        batch_op.create_index(batch_op.f('ix_takvim_hatirlatma_user_id'), ['user_id'], unique=False)

    op.create_table('bakim_kaydi',
    sa.Column('ekipman_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('aciklama', sa.String(length=500), nullable=True),
    sa.Column('calisma_saati', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ekipman_id'], ['ekipman.id'], name=op.f('fk_bakim_kaydi_ekipman_id_ekipman')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bakim_kaydi'))
    )
    with op.batch_alter_table('bakim_kaydi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bakim_kaydi_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_bakim_kaydi_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('cari_mahsup',
    sa.Column('borc_hareket_id', sa.Integer(), nullable=False),
    sa.Column('alacak_hareket_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alacak_hareket_id'], ['cari_hareket.id'], name=op.f('fk_cari_mahsup_alacak_hareket_id_cari_hareket'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['borc_hareket_id'], ['cari_hareket.id'], name=op.f('fk_cari_mahsup_borc_hareket_id_cari_hareket'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cari_mahsup'))
    )
    with op.batch_alter_table('cari_mahsup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cari_mahsup_alacak_hareket_id'), ['alacak_hareket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_mahsup_borc_hareket_id'), ['borc_hareket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_mahsup_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_mahsup_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_cari_mahsup_tarih'), ['tarih'], unique=False)

    op.create_table('kiralama_kalemi',
    sa.Column('kiralama_id', sa.Integer(), nullable=False),
    sa.Column('ekipman_id', sa.Integer(), nullable=True),
    sa.Column('is_dis_tedarik_ekipman', sa.Boolean(), nullable=True),
    sa.Column('harici_ekipman_tipi', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_marka', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_model', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_seri_no', sa.String(length=100), nullable=True),
    sa.Column('harici_ekipman_kapasite', sa.Integer(), nullable=True),
    sa.Column('harici_ekipman_yukseklik', sa.Integer(), nullable=True),
    sa.Column('harici_ekipman_uretim_yili', sa.Integer(), nullable=True),
    sa.Column('harici_ekipman_tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('kiralama_baslangici', sa.Date(), nullable=False),
    sa.Column('kiralama_bitis', sa.Date(), nullable=False),
    sa.Column('kiralama_brm_fiyat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kiralama_alis_fiyat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kiralama_alis_kdv', sa.Integer(), nullable=True),
    sa.Column('is_oz_mal_nakliye', sa.Boolean(), nullable=True),
    sa.Column('is_harici_nakliye', sa.Boolean(), nullable=True),
    sa.Column('nakliye_satis_fiyat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('donus_nakliye_fatura_et', sa.Boolean(), nullable=False),
    sa.Column('donus_nakliye_satis_fiyat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nakliye_alis_fiyat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nakliye_alis_kdv', sa.Integer(), nullable=True),
    sa.Column('nakliye_satis_kdv', sa.Integer(), nullable=True),
    sa.Column('nakliye_alis_tevkifat_oran', sa.String(length=10), nullable=True),
    sa.Column('nakliye_satis_tevkifat_oran', sa.String(length=10), nullable=True),
    sa.Column('nakliye_tedarikci_id', sa.Integer(), nullable=True),
    sa.Column('nakliye_araci_id', sa.Integer(), nullable=True),
    sa.Column('sonlandirildi', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('versiyon_no', sa.Integer(), nullable=False),
    sa.Column('degisim_nedeni', sa.String(length=50), nullable=True),
    sa.Column('degisim_tarihi', sa.DateTime(), nullable=True),
    sa.Column('cikis_saati', sa.Integer(), nullable=True),
    sa.Column('donus_saati', sa.Integer(), nullable=True),
    sa.Column('degisim_aciklama', sa.Text(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ekipman_id'], ['ekipman.id'], name=op.f('fk_kiralama_kalemi_ekipman_id_ekipman')),
    sa.ForeignKeyConstraint(['harici_ekipman_tedarikci_id'], ['firma.id'], name=op.f('fk_kiralama_kalemi_harici_ekipman_tedarikci_id_firma')),
    sa.ForeignKeyConstraint(['kiralama_id'], ['kiralama.id'], name=op.f('fk_kiralama_kalemi_kiralama_id_kiralama')),
    sa.ForeignKeyConstraint(['nakliye_araci_id'], ['ekipman.id'], name=op.f('fk_kiralama_kalemi_nakliye_araci_id_ekipman')),
    sa.ForeignKeyConstraint(['nakliye_tedarikci_id'], ['firma.id'], name=op.f('fk_kiralama_kalemi_nakliye_tedarikci_id_firma')),
    sa.ForeignKeyConstraint(['parent_id'], ['kiralama_kalemi.id'], name=op.f('fk_kiralama_kalemi_parent_id_kiralama_kalemi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kiralama_kalemi'))
    )
    with op.batch_alter_table('kiralama_kalemi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiralama_kalemi_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiralama_kalemi_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('nakliye',
    sa.Column('kiralama_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('nakliye_tipi', sa.String(length=20), nullable=True),
    sa.Column('arac_id', sa.Integer(), nullable=True),
    sa.Column('taseron_firma_id', sa.Integer(), nullable=True),
    sa.Column('guzergah', sa.String(length=200), nullable=False),
    sa.Column('plaka', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('toplam_tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taseron_maliyet', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cari_islendi_mi', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['arac_id'], ['araclar.id'], name=op.f('fk_nakliye_arac_id_araclar')),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name=op.f('fk_nakliye_firma_id_firma')),
    sa.ForeignKeyConstraint(['kiralama_id'], ['kiralama.id'], name=op.f('fk_nakliye_kiralama_id_kiralama'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taseron_firma_id'], ['firma.id'], name=op.f('fk_nakliye_taseron_firma_id_firma')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nakliye'))
    )
    with op.batch_alter_table('nakliye', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nakliye_cari_islendi_mi'), ['cari_islendi_mi'], unique=False)

    op.create_table('odeme',
    sa.Column('firma_musteri_id', sa.Integer(), nullable=False),
    sa.Column('kasa_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('yon', sa.String(length=20), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("yon IN ('tahsilat', 'odeme')", name=op.f('ck_odeme_check_odeme_yon')),
    sa.ForeignKeyConstraint(['firma_musteri_id'], ['firma.id'], name=op.f('fk_odeme_firma_musteri_id_firma')),
    sa.ForeignKeyConstraint(['kasa_id'], ['kasa.id'], name=op.f('fk_odeme_kasa_id_kasa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odeme'))
    )
    with op.batch_alter_table('odeme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odeme_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_odeme_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('stok_hareket',
    sa.Column('stok_karti_id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('adet', sa.Integer(), nullable=False),
    sa.Column('birim_fiyat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('hareket_tipi', sa.String(length=20), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name=op.f('fk_stok_hareket_firma_id_firma')),
    sa.ForeignKeyConstraint(['stok_karti_id'], ['stok_karti.id'], name=op.f('fk_stok_hareket_stok_karti_id_stok_karti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stok_hareket'))
    )
    with op.batch_alter_table('stok_hareket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stok_hareket_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_stok_hareket_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('sube_transferleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('ekipman_id', sa.Integer(), nullable=False),
    sa.Column('gonderen_sube_id', sa.Integer(), nullable=False),
    sa.Column('alan_sube_id', sa.Integer(), nullable=False),
    sa.Column('arac_id', sa.Integer(), nullable=False),
    sa.Column('neden', sa.String(length=50), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alan_sube_id'], ['subeler.id'], name=op.f('fk_sube_transferleri_alan_sube_id_subeler')),
    sa.ForeignKeyConstraint(['arac_id'], ['araclar.id'], name=op.f('fk_sube_transferleri_arac_id_araclar')),
    sa.ForeignKeyConstraint(['ekipman_id'], ['ekipman.id'], name=op.f('fk_sube_transferleri_ekipman_id_ekipman')),
    sa.ForeignKeyConstraint(['gonderen_sube_id'], ['subeler.id'], name=op.f('fk_sube_transferleri_gonderen_sube_id_subeler')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sube_transferleri'))
    )
    op.create_table('hizmet_kaydi',
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('nakliye_id', sa.Integer(), nullable=True),
    sa.Column('ozel_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('yon', sa.String(length=20), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('aciklama', sa.String(length=250), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('kiralama_alis_kdv', sa.Integer(), nullable=True),
    sa.Column('nakliye_alis_kdv', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("yon IN ('gelen', 'giden')", name=op.f('ck_hizmet_kaydi_check_hizmet_yon')),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name=op.f('fk_hizmet_kaydi_firma_id_firma')),
    sa.ForeignKeyConstraint(['nakliye_id'], ['nakliye.id'], name=op.f('fk_hizmet_kaydi_nakliye_id_nakliye'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hizmet_kaydi'))
    )
    with op.batch_alter_table('hizmet_kaydi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hizmet_kaydi_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_hizmet_kaydi_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('kullanilan_parca',
    sa.Column('bakim_kaydi_id', sa.Integer(), nullable=False),
    sa.Column('stok_karti_id', sa.Integer(), nullable=False),
    sa.Column('kullanilan_adet', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bakim_kaydi_id'], ['bakim_kaydi.id'], name=op.f('fk_kullanilan_parca_bakim_kaydi_id_bakim_kaydi')),
    sa.ForeignKeyConstraint(['stok_karti_id'], ['stok_karti.id'], name=op.f('fk_kullanilan_parca_stok_karti_id_stok_karti')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kullanilan_parca'))
    )
    with op.batch_alter_table('kullanilan_parca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kullanilan_parca_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_kullanilan_parca_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('makine_degisim',
    sa.Column('kiralama_id', sa.Integer(), nullable=False),
    sa.Column('eski_kalem_id', sa.Integer(), nullable=False),
    sa.Column('yeni_kalem_id', sa.Integer(), nullable=False),
    sa.Column('eski_ekipman_id', sa.Integer(), nullable=True),
    sa.Column('yeni_ekipman_id', sa.Integer(), nullable=True),
    sa.Column('neden', sa.String(length=50), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('eski_ekipman_donus_saati', sa.Integer(), nullable=True),
    sa.Column('yeni_ekipman_cikis_saati', sa.Integer(), nullable=True),
    sa.Column('servis_kayit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eski_ekipman_id'], ['ekipman.id'], name=op.f('fk_makine_degisim_eski_ekipman_id_ekipman')),
    sa.ForeignKeyConstraint(['eski_kalem_id'], ['kiralama_kalemi.id'], name=op.f('fk_makine_degisim_eski_kalem_id_kiralama_kalemi')),
    sa.ForeignKeyConstraint(['kiralama_id'], ['kiralama.id'], name=op.f('fk_makine_degisim_kiralama_id_kiralama')),
    sa.ForeignKeyConstraint(['yeni_ekipman_id'], ['ekipman.id'], name=op.f('fk_makine_degisim_yeni_ekipman_id_ekipman')),
    sa.ForeignKeyConstraint(['yeni_kalem_id'], ['kiralama_kalemi.id'], name=op.f('fk_makine_degisim_yeni_kalem_id_kiralama_kalemi')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_makine_degisim'))
    )
    with op.batch_alter_table('makine_degisim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_makine_degisim_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_makine_degisim_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('hakedis',
    sa.Column('hakedis_no', sa.String(length=50), nullable=True),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('belge_tipi', sa.String(length=20), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('kiralama_id', sa.Integer(), nullable=False),
    sa.Column('proje_adi', sa.String(length=200), nullable=True),
    sa.Column('santiye_adresi', sa.Text(), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('duzenleme_tarihi', sa.Date(), nullable=False),
    sa.Column('duzenleme_saati', sa.Time(), nullable=False),
    sa.Column('fatura_senaryosu', sa.String(length=20), nullable=True),
    sa.Column('fatura_tipi', sa.String(length=20), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('kur_degeri', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('siparis_referans_no', sa.String(length=50), nullable=True),
    sa.Column('siparis_referans_tarihi', sa.Date(), nullable=True),
    sa.Column('toplam_matrah', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('toplam_kdv', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('toplam_tevkifat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('genel_toplam', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('is_faturalasti', sa.Boolean(), nullable=True),
    sa.Column('cari_hareket_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("belge_tipi IN ('EFATURA', 'EARSIV')", name=op.f('ck_hakedis_ck_hakedis_belge_tipi')),
    sa.CheckConstraint("durum IN ('taslak', 'onaylandi', 'faturalasti', 'iptal')", name=op.f('ck_hakedis_ck_hakedis_durum')),
    sa.CheckConstraint("fatura_senaryosu IN ('TEMELFATURA', 'TICARIFATURA')", name=op.f('ck_hakedis_ck_hakedis_senaryo')),
    sa.CheckConstraint("fatura_tipi IN ('SATIS', 'IADE', 'TEVKIFAT', 'OZELMATRAH', 'ISTISNA')", name=op.f('ck_hakedis_ck_hakedis_tip')),
    sa.ForeignKeyConstraint(['cari_hareket_id'], ['hizmet_kaydi.id'], name=op.f('fk_hakedis_cari_hareket_id_hizmet_kaydi')),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name=op.f('fk_hakedis_firma_id_firma')),
    sa.ForeignKeyConstraint(['kiralama_id'], ['kiralama.id'], name=op.f('fk_hakedis_kiralama_id_kiralama')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hakedis')),
    sa.UniqueConstraint('uuid', name=op.f('uq_hakedis_uuid'))
    )
    with op.batch_alter_table('hakedis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hakedis_durum'), ['durum'], unique=False)
        batch_op.create_index(batch_op.f('ix_hakedis_fatura_no'), ['fatura_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_hakedis_hakedis_no'), ['hakedis_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_hakedis_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_hakedis_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('hakedis_kalemi',
    sa.Column('hakedis_id', sa.Integer(), nullable=False),
    sa.Column('kiralama_kalemi_id', sa.Integer(), nullable=False),
    sa.Column('ekipman_id', sa.Integer(), nullable=False),
    sa.Column('mal_hizmet_adi', sa.String(length=250), nullable=False),
    sa.Column('mal_hizmet_aciklama', sa.String(length=500), nullable=True),
    sa.Column('miktar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('birim_tipi', sa.String(length=10), nullable=True),
    sa.Column('birim_kodu', sa.String(length=10), nullable=False),
    sa.Column('birim_fiyat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ara_toplam', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('iskonto_orani', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iskonto_tutari', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('kdv_tutari', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tevkifat_kodu', sa.String(length=10), nullable=True),
    sa.Column('tevkifat_orani', sa.Integer(), nullable=True),
    sa.Column('tevkifat_pay', sa.Integer(), nullable=True),
    sa.Column('tevkifat_payda', sa.Integer(), nullable=True),
    sa.Column('tevkifat_tutari', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ozel_matrah_tutari', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ozel_matrah_kdv_orani', sa.Integer(), nullable=True),
    sa.Column('istisna_kodu', sa.String(length=10), nullable=True),
    sa.Column('istisna_nedeni', sa.String(length=250), nullable=True),
    sa.Column('satir_toplami', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("birim_tipi IN ('DAY', 'MON', 'C62', 'HUR')", name=op.f('ck_hakedis_kalemi_ck_kalem_birim')),
    sa.ForeignKeyConstraint(['ekipman_id'], ['ekipman.id'], name=op.f('fk_hakedis_kalemi_ekipman_id_ekipman')),
    sa.ForeignKeyConstraint(['hakedis_id'], ['hakedis.id'], name=op.f('fk_hakedis_kalemi_hakedis_id_hakedis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hakedis_kalemi'))
    )
    with op.batch_alter_table('hakedis_kalemi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hakedis_kalemi_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_hakedis_kalemi_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hakedis_kalemi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hakedis_kalemi_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_hakedis_kalemi_is_active'))

    op.drop_table('hakedis_kalemi')
    with op.batch_alter_table('hakedis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hakedis_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_hakedis_is_active'))
        batch_op.drop_index(batch_op.f('ix_hakedis_hakedis_no'))
        batch_op.drop_index(batch_op.f('ix_hakedis_fatura_no'))
        batch_op.drop_index(batch_op.f('ix_hakedis_durum'))

    op.drop_table('hakedis')
    with op.batch_alter_table('makine_degisim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_makine_degisim_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_makine_degisim_is_active'))

    op.drop_table('makine_degisim')
    with op.batch_alter_table('kullanilan_parca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanilan_parca_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_kullanilan_parca_is_active'))

    op.drop_table('kullanilan_parca')
    with op.batch_alter_table('hizmet_kaydi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hizmet_kaydi_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_hizmet_kaydi_is_active'))

    op.drop_table('hizmet_kaydi')
    op.drop_table('sube_transferleri')
    with op.batch_alter_table('stok_hareket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stok_hareket_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stok_hareket_is_active'))

    op.drop_table('stok_hareket')
    with op.batch_alter_table('odeme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odeme_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_odeme_is_active'))

    op.drop_table('odeme')
    with op.batch_alter_table('nakliye', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nakliye_cari_islendi_mi'))

    op.drop_table('nakliye')
    with op.batch_alter_table('kiralama_kalemi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiralama_kalemi_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_kiralama_kalemi_chain_id'))

    op.drop_table('kiralama_kalemi')
    with op.batch_alter_table('cari_mahsup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cari_mahsup_tarih'))
        batch_op.drop_index(batch_op.f('ix_cari_mahsup_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_cari_mahsup_is_active'))
        batch_op.drop_index(batch_op.f('ix_cari_mahsup_borc_hareket_id'))
        batch_op.drop_index(batch_op.f('ix_cari_mahsup_alacak_hareket_id'))

    op.drop_table('cari_mahsup')
    with op.batch_alter_table('bakim_kaydi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bakim_kaydi_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bakim_kaydi_is_active'))

    op.drop_table('bakim_kaydi')
    with op.batch_alter_table('takvim_hatirlatma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_takvim_hatirlatma_user_id'))
        batch_op.drop_index(batch_op.f('ix_takvim_hatirlatma_tarih'))
        batch_op.drop_index(batch_op.f('ix_takvim_hatirlatma_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_takvim_hatirlatma_is_active'))

    op.drop_table('takvim_hatirlatma')
    with op.batch_alter_table('stok_karti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stok_karti_parca_kodu'))
        batch_op.drop_index(batch_op.f('ix_stok_karti_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stok_karti_is_active'))

    op.drop_table('stok_karti')
    with op.batch_alter_table('kiralama', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiralama_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_kiralama_is_active'))

    op.drop_table('kiralama')
    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kasa_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_kasa_is_active'))

    op.drop_table('kasa')
    with op.batch_alter_table('ekipman', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ekipman_seri_no'))
        batch_op.drop_index(batch_op.f('ix_ekipman_kod'))
        batch_op.drop_index(batch_op.f('ix_ekipman_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_ekipman_is_active'))

    op.drop_table('ekipman')
    with op.batch_alter_table('cari_hareket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cari_hareket_yon'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_vade_tarihi'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_tarih'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_kaynak_modul'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_kaynak_id'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_is_active'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_firma_id'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_durum'))
        batch_op.drop_index(batch_op.f('ix_cari_hareket_belge_no'))

    op.drop_table('cari_hareket')
    with op.batch_alter_table('araclar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_araclar_plaka'))
        batch_op.drop_index(batch_op.f('ix_araclar_is_deleted'))

    op.drop_table('araclar')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('subeler')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_log_username'))
        batch_op.drop_index(batch_op.f('ix_operation_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_success'))
        batch_op.drop_index(batch_op.f('ix_operation_log_module'))
        batch_op.drop_index(batch_op.f('ix_operation_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_operation_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_operation_log_action'))

    op.drop_table('operation_log')
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firma_vergi_no'))
        batch_op.drop_index(batch_op.f('ix_firma_tckn'))
        batch_op.drop_index(batch_op.f('ix_firma_is_tedarikci'))
        batch_op.drop_index(batch_op.f('ix_firma_is_musteri'))
        batch_op.drop_index(batch_op.f('ix_firma_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_firma_is_active'))
        batch_op.drop_index(batch_op.f('ix_firma_firma_adi'))
        batch_op.drop_index(batch_op.f('ix_firma_etiket_uuid'))
        batch_op.drop_index(batch_op.f('ix_firma_eposta'))

    op.drop_table('firma')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_app_settings_is_active'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
