"""arac_bakim_sonraki_bakim_turu_ve_km_ekle

Revision ID: db93d0cf03a2
Revises: d2a4f6c8e1b3
Create Date: 2026-04-05 08:46:26.314887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db93d0cf03a2'
down_revision = 'd2a4f6c8e1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arac_bakim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sonraki_bakim_turu', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sonraki_bakim_km', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arac_bakim', schema=None) as batch_op:
        batch_op.drop_column('sonraki_bakim_km')
        batch_op.drop_column('sonraki_bakim_turu')

    # ### end Alembic commands ###
