"""Odeme tablosuna islem_tarihi ekle

Revision ID: e862a8e8eafc
Revises: a91f4c2d8e77
Create Date: 2026-04-15 18:48:54.462805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e862a8e8eafc'
down_revision = 'a91f4c2d8e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT: hizmet_kaydi'nin islem_tarihi sütunu korunuyor (a91f4c2d8e77'de eklendi)

    with op.batch_alter_table('nakliye', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nakliye_is_active'), ['is_active'], unique=False)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_by_id')

    with op.batch_alter_table('odeme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('islem_tarihi', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_odeme_islem_tarihi'), ['islem_tarihi'], unique=False)

    with op.batch_alter_table('personel_izin', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_personel_izin_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('personel_maas_donemleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personel_maas_donemleri_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_personel_maas_donemleri_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('sube_giderleri', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_sube_giderleri_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sube_giderleri_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('sube_sabit_gider_donemleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sube_sabit_gider_donemleri_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('sube_transferleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sube_transferleri_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sube_transferleri_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('subeler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subeler_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_subeler_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_is_deleted'), ['is_deleted'], unique=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_is_deleted'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('subeler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subeler_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_subeler_is_active'))

    with op.batch_alter_table('sube_transferleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sube_transferleri_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sube_transferleri_is_active'))

    with op.batch_alter_table('sube_sabit_gider_donemleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sube_sabit_gider_donemleri_is_deleted'))

    with op.batch_alter_table('sube_giderleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sube_giderleri_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sube_giderleri_is_active'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('personel_maas_donemleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personel_maas_donemleri_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_personel_maas_donemleri_is_active'))

    with op.batch_alter_table('personel_izin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personel_izin_is_active'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('odeme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odeme_islem_tarihi'))
        batch_op.drop_column('islem_tarihi')

    with op.batch_alter_table('nakliye', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('deleted_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_nakliye_is_active'))

    # NOT: hizmet_kaydi'nin islem_tarihi sütunu korunuyor

    # ### end Alembic commands ###
