name: Deploy to Server

on:
  push:
    branches:
      - main  # Burayı kullandığınız ana branch adı (main veya master) yapın

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/kiralama_projesi_v4
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            export FLASK_APP=run.py

            echo ">>> Alembic migration uygulanıyor..."
            python -m flask db upgrade
            echo ">>> Migration tamamlandi."

            systemctl restart kiralama_test.service